from fastapi import FastAPI, Request, Form, File, UploadFile, Response, Header
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from backend.ai_engine import generate_ai_response, generate_quiz_questions
from backend.rag_engine import extract_text_from_pdf
from typing import Optional
import json

app = FastAPI(title="Kognit Academic Assistant")

app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

active_pdf_contexts = {}

@app.get("/", response_class=HTMLResponse)
async def read_root(request: Request):
    return templates.TemplateResponse(request=request, name="index.html")

@app.post("/api/pdf/upload")
async def upload_pdf(file: UploadFile = File(...)):
    file_bytes = await file.read()
    pdf_text = extract_text_from_pdf(file_bytes)
    active_pdf_contexts["current_pdf"] = pdf_text
    return {"status": "success", "filename": file.filename, "length": len(pdf_text)}

@app.post("/api/chat")
async def chat_endpoint(
    prompt: str = Form(...),
    mode: str = Form("direct"),
    board: str = Form("NCTB Bangla Medium"),
    user_class: str = Form("Class 9-10 / SSC"),
    stream: str = Form("Science"),
    image: Optional[UploadFile] = File(None),
    authorization: Optional[str] = Header(None)
):
    # authorization header থেকে পাওয়া jwt token যাচাই করার কোড থাকবে
    image_bytes = None
    if image:
        image_bytes = await image.read()

    pdf_context = active_pdf_contexts.get("current_pdf", "")

    response = generate_ai_response(
        prompt=prompt,
        mode=mode,
        board=board,
        user_class=user_class,
        stream=stream,
        image_bytes=image_bytes,
        pdf_context=pdf_context
    )
    return {"reply": response}

@app.post("/api/quiz/generate")
async def quiz_generate_endpoint(
    board: str = Form("NCTB Bangla Medium"),
    user_class: str = Form("Class 9-10 / SSC"),
    subject: str = Form("Science"),
    topic: str = Form("General Practice"),
    count: int = Form(5)
):
    questions = generate_quiz_questions(
        board=board,
        user_class=user_class,
        subject=subject,
        topic=topic,
        count=count
    )
    return {"questions": questions}

@app.post("/api/export/markdown")
async def export_markdown_endpoint(
    title: str = Form("Kognit_Study_Note"),
    chat_data: str = Form("[]")
):
    try:
        messages = json.loads(chat_data)
        md_content = f"# {title}\n\n*Generated by Kognit AI Assistant*\n\n---\n\n"

        for msg in messages:
            role_title = "👤 User" if msg.get("role") == "user" else "🤖 Kognit AI"
            text = msg.get("text", "")
            md_content += f"### {role_title}\n{text}\n\n---\n\n"

        headers = {
            "content-disposition": f'attachment; filename={title.replace(" ", "_")}.md'
        }
        return Response(content=md_content, media_type="text/markdown", headers=headers)
    except Exception as e:
        return Response(content=f"Error exporting markdown: {str(e)}", status_code=500)